version: '3.3'
services:
  nginx:
    image: nginx:1.19.6-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "90:90"
      - "92:92"
      - "82:82"
      - "443:443"
    volumes:
      - builder-staging:/usr/share/nginx/staging
      - builder-dev:/usr/share/nginx/dev
      - builder-docs:/usr/share/nginx/docs
      - builder-role:/usr/share/nginx/role
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx.docker
volumes:
  builder-staging:
  builder-dev:
  builder-docs:
  builder-role:
networks:
  nginx.docker:
    external: true
