export const services = {
	all: {
		nodes: [
			{
				id: 'npt-1',
				name: 'Công ty Cổ Phần Fujinet Systems',
				level: 0,
				childrenNum: 150,
				tag: '',
			},
			{
				id: 'npt-2',
				name: 'Công ty Cổ phần GMO-Z.com RUNSYSTEM',
				level: 0,
				childrenNum: 250,
				tag: '',
			},
			{
				id: 'npt-3',
				name: 'Công ty TNHH Harvey Nash Việt Nam (NashTech Vietnam)',
				level: 0,
				childrenNum: 10,
				tag: '',
			},
			{
				id: 'npt-4',
				name: 'Công ty TNHH KMS Technology Việt Nam',
				level: 0,
				childrenNum: 77,
				tag: '',
			},
			{
				id: 'npt-5',
				name: 'Công ty Cổ phần Phần mềm LUVINA',
				level: 0,
				childrenNum: 90,
				tag: '',
			},
			{
				id: 'npt-6',
				name: 'Công ty TNHH Giải pháp Phần \n mềm Tường Minh (TMA Solutions)',
				level: 0,
				childrenNum: 5,
				tag: '',
			},
			{
				id: 'npt-7',
				name: 'Công ty Cổ phần VNEXT HOLDINGS',
				level: 0,
				childrenNum: 125,
				tag: '',
			},
			{
				id: 'npt-8',
				name: 'KYANON Digital',
				level: 0,
				childrenNum: 100,
				tag: '',
			},
			{
				id: 'npt-8',
				name: 'Công ty TNHH SÀI GÒN BPO',
				level: 0,
				childrenNum: 350,
				tag: '',
			},
		],
		edges: [],
	},
	erp: {
		nodes: [
			{
				id: 'npt-1',
				name: 'Công ty Cổ Phần Fujinet Systems',
				level: 0,
				childrenNum: 50,
				tag: '',
			},
			{
				id: 'npt-2',
				name: 'Công ty Cổ phần GMO-Z.com RUNSYSTEM',
				level: 0,
				childrenNum: 210,
				tag: '',
			},
			{
				id: 'npt-3',
				name: 'Công ty TNHH Harvey Nash Việt Nam (NashTech Vietnam)',
				level: 0,
				childrenNum: 110,
				tag: '',
			},
			{
				id: 'npt-4',
				name: 'Công ty TNHH KMS Technology Việt Nam',
				level: 0,
				childrenNum: 771,
				tag: '',
			},
			{
				id: 'npt-5',
				name: 'Công ty Cổ phần Phần mềm LUVINA',
				level: 0,
				childrenNum: 120,
				tag: '',
			},
			{
				id: 'npt-6',
				name: 'Công ty TNHH Giải pháp Phần \n mềm Tường Minh (TMA Solutions)',
				level: 0,
				childrenNum: 125,
				tag: '',
			},
			{
				id: 'npt-7',
				name: 'Công ty Cổ phần VNEXT HOLDINGS',
				level: 0,
				childrenNum: 65,
				tag: '',
			},
			{
				id: 'npt-8',
				name: 'KYANON Digital',
				level: 0,
				childrenNum: 160,
				tag: '',
			},
			{
				id: 'npt-8',
				name: 'Công ty TNHH SÀI GÒN BPO',
				level: 0,
				childrenNum: 100,
				tag: '',
			},
		],
		edges: [],
	},
};
