export const dataTotalRevenueDeveloper = {
	ALL: {
		nodes: [
			{
				id: 'npt-1',
				name: 'Công ty Cổ Phần Fujinet Systems',
				level: 0,
				childrenNum: 280000000,
				tag: '',
			},
			{
				id: 'npt-2',
				name: 'Công ty Cổ phần GMO-Z.com RUNSYSTEM',
				level: 0,
				childrenNum: 369021000,
				tag: '',
			},
			{
				id: 'npt-3',
				name: 'Công ty TNHH Harvey Nash Việt Nam (NashTech Vietnam)',
				level: 0,
				childrenNum: 25632100,
				tag: '',
			},
			{
				id: 'npt-4',
				name: 'Công ty TNHH KMS Technology Việt Nam',
				level: 0,
				childrenNum: 450000120,
				tag: '',
			},
			{
				id: 'npt-5',
				name: 'Công ty Cổ phần Phần mềm LUVINA',
				level: 0,
				childrenNum: 105251140,
				tag: '',
			},
			{
				id: 'npt-6',
				name: 'Công ty TNHH Giải pháp Phần \n mềm Tường Minh (TMA Solutions)',
				level: 0,
				childrenNum: 100258100,
				tag: '',
			},
			{
				id: 'npt-7',
				name: 'Công ty Cổ phần VNEXT HOLDINGS',
				level: 0,
				childrenNum: 21528102,
				tag: '',
			},
			{
				id: 'npt-8',
				name: 'KYANON Digital',
				level: 0,
				childrenNum: 154258177,
				tag: '',
			},
			{
				id: 'npt-9',
				name: 'Công ty TNHH Giải pháp Tin học - IFI Solution',
				level: 0,
				childrenNum: 450000120,
				tag: '',
			},
			{
				id: 'npt-10',
				name: 'Công ty TNHH SÀI GÒN BPO',
				level: 0,
				childrenNum: 299874000,
				tag: '',
			},
		],
		edges: [],
	},
	MONTH: {
		nodes: [
			{
				id: 'npt-1',
				name: 'Nhà phát triển 1',
				level: 0,
				childrenNum: 3000,
				tag: 'npt-1',
			},
			{
				id: 'npt-2',
				name: 'Nhà phát triển 2',
				level: 0,
				childrenNum: 200,
				tag: 'npt-2',
			},
			{
				id: 'npt-3',
				name: 'Nhà phát triển 3',
				level: 0,
				childrenNum: 1000,
				tag: 'npt-3',
			},
			{
				id: 'npt-4',
				name: 'Nhà phát triển 4',
				level: 0,
				childrenNum: 1500,
				tag: 'npt-4',
			},
			// {
			// 	id: "reward",
			// 	name: "Thưởng",
			// 	level: 1,
			// 	childrenNum: 100000,
			// 	tag: "reward",
			// 	isLeaf: false,
			// 	tags: ["npt-2"],
			// },
			// {
			// 	id: "hard-work",
			// 	name: "Chăm chỉ",
			// 	level: 2,
			// 	isLeaf: true,
			// 	tags: ["npt-1"],
			// },
		],
		edges: [
			// {
			// 	source: "npt-3",
			// 	target: "npt-1",
			// },
		],
	},
	PRECIOUS: {
		nodes: [
			{
				id: 'npt-1',
				name: 'Nhà phát triển 1',
				level: 0,
				childrenNum: 5000,
				tag: 'npt-1',
			},
			{
				id: 'npt-2',
				name: 'Nhà phát triển 2',
				level: 0,
				childrenNum: 300,
				tag: 'npt-2',
			},
			{
				id: 'npt-3',
				name: 'Nhà phát triển 3',
				level: 0,
				childrenNum: 2000,
				tag: 'npt-3',
			},
			{
				id: 'npt-4',
				name: 'Nhà phát triển 4',
				level: 0,
				childrenNum: 1500,
				tag: 'npt-4',
			},
			// {
			// 	id: "reward",
			// 	name: "Thưởng",
			// 	level: 1,
			// 	childrenNum: 100000,
			// 	tag: "reward",
			// 	isLeaf: false,
			// 	tags: ["npt-2"],
			// },
			// {
			// 	id: "hard-work",
			// 	name: "Chăm chỉ",
			// 	level: 2,
			// 	isLeaf: true,
			// 	tags: ["npt-1"],
			// },
		],
		edges: [
			// {
			// 	source: "npt-3",
			// 	target: "npt-1",
			// },
		],
	},
	YEAR: {
		nodes: [
			{
				id: 'npt-1',
				name: 'Nhà phát triển 1',
				level: 0,
				childrenNum: 300,
				tag: 'npt-1',
			},
			{
				id: 'npt-2',
				name: 'Nhà phát triển 2',
				level: 0,
				childrenNum: 40,
				tag: 'npt-2',
			},
			{
				id: 'npt-3',
				name: 'Nhà phát triển 3',
				level: 0,
				childrenNum: 100,
				tag: 'npt-3',
			},
			{
				id: 'npt-4',
				name: 'Nhà phát triển 4',
				level: 0,
				childrenNum: 140,
				tag: 'npt-4',
			},
			// {
			// 	id: "reward",
			// 	name: "Thưởng",
			// 	level: 1,
			// 	childrenNum: 100000,
			// 	tag: "reward",
			// 	isLeaf: false,
			// 	tags: ["npt-2"],
			// },
			// {
			// 	id: "hard-work",
			// 	name: "Chăm chỉ",
			// 	level: 2,
			// 	isLeaf: true,
			// 	tags: ["npt-1"],
			// },
		],
		edges: [
			// {
			// 	source: "npt-3",
			// 	target: "npt-1",
			// },
		],
	},
};
