import {
	validateRequire,
	validateRequireInput,
	validateMaxLengthStr,
	validatePhoneNumber,
	validateEmail,
	validatePassword,
	validateNumber,
	validateNumberLength,
	validateMaxArraySelect,
	validateMaxLengthSelect,
	validateRegexCharSelect,
	validateCustomPattern,
	formatNormalizeCurrency,
	formatNormalizeNumber,
	validateUrl,
	formatNormalizeNumberZero,
	formatNormalizeTaxCode,
	validateStrLength,
	formatNormalizeStringSelect,
	validateCompareOldPassword,
	validateRequireCheckbox,
	validateFile,
	getFormError,
	formatNormalizeNumberOtherZero,
	validateRequireSelectItems,
	// validateMinMaxInputNumber,
	validateCode,
	formatNormalizeFloatNumber,
	validateRequireApplyService,
	validateMinInputNumber,
	validateMaxInputNumber,
	validateInputNumAndComma,
	validateMaxValueArr,
	validateMaxValue,
	validateQuanlitySub,
} from './Validator';
import CheckError from './CheckError';
import {
	isInt,
	convertBusinessScale,
	convertToNumber,
	convertToArrObj,
	checkAlertPopup,
	convertTime,
	convertToArrNumber,
	convertToArrObjForPricing,
} from './isInt';

export {
	CheckError,
	validateRequire,
	validateRequireInput,
	validateMaxLengthStr,
	validatePhoneNumber,
	validateEmail,
	validatePassword,
	validateNumber,
	validateNumberLength,
	validateMaxArraySelect,
	validateMaxLengthSelect,
	validateRegexCharSelect,
	validateCustomPattern,
	formatNormalizeCurrency,
	formatNormalizeNumber,
	validateUrl,
	formatNormalizeNumberZero,
	formatNormalizeTaxCode,
	validateStrLength,
	formatNormalizeStringSelect,
	validateCompareOldPassword,
	validateRequireCheckbox,
	validateFile,
	getFormError,
	formatNormalizeNumberOtherZero,
	validateRequireSelectItems,
	isInt,
	convertBusinessScale,
	// validateMinMaxInputNumber,
	convertToNumber,
	convertToArrObj,
	validateCode,
	formatNormalizeFloatNumber,
	checkAlertPopup,
	convertTime,
	validateRequireApplyService,
	convertToArrNumber,
	validateMinInputNumber,
	validateMaxInputNumber,
	validateInputNumAndComma,
	validateMaxValueArr,
	convertToArrObjForPricing,
	validateMaxValue,
	validateQuanlitySub,
};
